// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULJbl0NxmkxwzKXv_RsqzJOVuSDf48y8',
    appId: '1:1005113099043:web:3733c1a72cd0a9698fc296',
    messagingSenderId: '1005113099043',
    projectId: 'socialmediaclone-6b37c',
    authDomain: 'socialmediaclone-6b37c.firebaseapp.com',
    storageBucket: 'socialmediaclone-6b37c.firebasestorage.app',
    measurementId: 'G-MQ5T4698EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2eICnz01xe8yvOgsS27XuDaF6D7krp4',
    appId: '1:1005113099043:android:8c56e92935376f0d8fc296',
    messagingSenderId: '1005113099043',
    projectId: 'socialmediaclone-6b37c',
    storageBucket: 'socialmediaclone-6b37c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeq40B0TNsc1kNuL1VY9vCInQ0HBXWAkw',
    appId: '1:1005113099043:ios:c3f072e63e0412dc8fc296',
    messagingSenderId: '1005113099043',
    projectId: 'socialmediaclone-6b37c',
    storageBucket: 'socialmediaclone-6b37c.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaClone',
  );
}
